### ISSUE TITLE
Display Graphs Window

### ISSUE THREAD

**Issue by michaelm536** [SIU-CS/Red_Dusk-Production#15]
Goal: The website will have a window to display graphs

Description:
The website will have a window to display graphs that the user has created via their executed R-files (R-IDEs)

Origin: Team Meeting III

Version: 1.0    Date: 02/15/2018    Priority: 2

**Comment by amcowden97** [comment]
Users can now display .pdf file graphs onto the primary page under the graph tab. These will only be valid of the last run.
