### ISSUE TITLE
Syntax Highlighting

### ISSUE THREAD

**Issue by jmsieling** [SIU-CS/Red_Dusk-Production#50]
Goal: 
The editor window contains syntax highlighting for the user

Description: 
The website will have syntax and error highlighting, along with line numbers and other miscellaneous properties of an IDE, to help make it more user-friendly

Origin: Sprint 2 Planning meeting

Version: 1.0 3/22/18 Priority 2

**Comment by michaelm536** [comment]
This was accomplished by adding in the new Ace editor technology. This accomplishes all that we needed it to do and looks aesthetically pleasing as well!
