### ISSUE TITLE
Creating Graphs

### ISSUE THREAD

**Issue by michaelm536** [SIU-CS/Red_Dusk-Production#6]
Goal: User can create graphs using their R file (or RIDE)

Description: Users can create graphs using their editor or command line.

Origin: Team Meeting I

Version: 1.0    Date: 02/10/2018    Priority: 2

**Comment by amcowden97** [comment]
Users can create graphs from the R code given and display them on the output panel of the Code Runner Page. Account holders can also choose to save this graph into their account
